---
loader: taskgraph.loader.transform:loader

transforms:
  - firefox_tv_taskgraph.signing:transforms
  - taskgraph.transforms.task:transforms

jobs:
  push:
    label: Sign for Github
    description: ''
    worker-type: signing
    run-on-tasks-for: [github-release]
    dependencies:
      build: build-release
    worker:
      upstream-artifacts:
        - taskType: build
          paths:
            - public/build/target.apk
          formats:
            - autograph_apk
          taskId:
            task-reference: <build>
