# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
  - firefox_tv_taskgraph.signing:transforms
  - taskgraph.transforms.task:transforms

jobs:
  sign:
    label: Sign for Github
    description: ''
    worker-type: signing
    run-on-tasks-for: [github-release]
    dependencies:
      build: build-release
    worker:
      upstream-artifacts:
        - taskType: build
          paths:
            - public/build/target.apk
          formats:
            - autograph_apk
          taskId:
            task-reference: <build>
