---
trust-domain: mobile
task-priority: highest

taskgraph:
  register: firefox_tv_taskgraph:register
  repositories:
    mobile:
      name: "Firefox TV"
  cached-task-prefix: project.mobile.firefox-tv

workers:
  aliases:
    b-android:
      provisioner: aws-provisioner-v1
      implementation: docker-worker
      os: linux
      worker-type: 'mobile-{level}-b-firefox-tv'
    images:
      provisioner: aws-provisioner-v1
      implementation: docker-worker
      os: linux
      worker-type: 'mobile-{level}-images'
    dep-signing:
      provisioner: scriptworker-prov-v1
      implementation: scriptworker-signing
      os: scriptworker
      worker-type: mobile-signing-dep-v1
    signing:
      provisioner: scriptworker-prov-v1
      implementation: scriptworker-signing
      os: scriptworker
      worker-type:
        by-level:
          "3": mobile-signing-v1
          default: mobile-signing-dep-v1
    push-apk:
      provisioner: scriptworker-prov-v1
      implementation: scriptworker-push-apk
      os: scriptworker
      worker-type:
        by-level:
          "3": mobile-push-apk-v1
          default: mobile-push-apk-dep-v1

scriptworker:
  scope-prefix: project:mobile:firefox-tv:releng
