# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
  - firefox_tv_taskgraph.transforms.email:transforms
  - taskgraph.transforms.task:transforms

jobs:
  email:
    label: Email that automation is complete
    description: ''
    worker-type: succeed
    run-on-tasks-for: [github-release]
    dependencies:
      build: build-release
      sign: 'Sign for Github'
      push: 'Push to Amazon'
    worker:
      to-address: firefox-tv@mozilla.com
      content:
        by-release-type:
          production: |
            Automation for this release is ready. Please:
            * Download [the signed APK](<sign/public/build/target.apk>) and attach it to the [Github release](https://github.com/mozilla-mobile/firefox-tv/releases/tag/{tag})
            * [Deploy the new release on Amazon](https://developer.amazon.com/apps-and-games/console/app/amzn1.devportal.mobileapp.7f334089688646ef8953d041021029c9/release/amzn1.devportal.apprelease.4ca3990c43f34101bf5729543343747a/general/detail)
          lat: |
            Automation for this release is ready. Please:
            * Download [the signed APK](<sign/public/build/target.apk>) and attach it to the [Github release](https://github.com/mozilla-mobile/firefox-tv/releases/tag/{tag})
            * Download [the unsigned APK](<build/public/build/target.apk>) and [deploy the new release on Amazon](https://developer.amazon.com/apps-and-games/console/app/amzn1.devportal.mobileapp.7f334089688646ef8953d041021029c9/release/amzn1.devportal.apprelease.4ca3990c43f34101bf5729543343747a/general/detail)
      subject: "Release {tag} is ready for deployment"
